In [1]:
import torch
import numpy as np
import pytest

In [2]:
tensor = np.array([[[0.3, 0.9, 0.1],
                    [0.8, 0.2, 0.1],
                    [0.4, 0.3, 0.9]],
                   [[0.6, 0.9, 0.5],
                    [0.5, 0.6, 0.4],
                    [0.1, 0.4, 0.1]]])
tensor = np.random.random((2, 3, 3))
torch_tensor = torch.from_numpy(tensor)
#print(tensor)
print(tensor.shape)

(2, 3, 3)


### Note:
The numpy implementation (unfold method) is simple re-implementation of the tensorly unfold method.<br>
The pytorch implementation is converted version of that unfold method.

In [3]:
def unfold(tensor, mode):
    x = np.moveaxis(tensor, mode, 0)
    print(x)
    return np.reshape(np.moveaxis(tensor, mode, 0), (tensor.shape[mode], -1))

In [36]:
def moveaxis(tensor: torch.Tensor, source: int, destination: int) -> torch.Tensor:
    dim = tensor.dim()
    perm = list(range(dim))
    if destination < 0:
        destination += dim
    perm.pop(source)
    perm.insert(destination, source)
    return tensor.permute(*perm)

In [37]:
def pytorch_unfold(tensor, mode):
    #print(tensor.transpose(mode, 0).shape)
    #t = tensor.transpose(mode, 0)
    #x = tensor[:, 0]
    #tensor[:, 0] = tensor[:, mode]
    #tensor[:, mode] = x
    #print(tensor)
    #t = tensor.unsqueeze(0).transpose(0, mode)
    t = moveaxis(tensor, mode, 0)
    print(t)
    return t.reshape(t.shape[mode], -1).T

In [40]:
mode = 2
u1 = unfold(tensor, mode)
#print(u)

[[[0.09137356 0.09137356 0.0823618 ]
  [0.26015999 0.26015999 0.15970755]]

 [[0.89994109 0.89994109 0.74503774]
  [0.86448336 0.86448336 0.81860706]]

 [[0.23391911 0.23391911 0.16136592]
  [0.64704274 0.64704274 0.72591513]]]


In [41]:
u2 =  pytorch_unfold(torch_tensor, mode).detach().cpu().numpy()

tensor([[[0.0914, 0.0914, 0.0824],
         [0.2602, 0.2602, 0.1597]],

        [[0.8999, 0.8999, 0.7450],
         [0.8645, 0.8645, 0.8186]],

        [[0.2339, 0.2339, 0.1614],
         [0.6470, 0.6470, 0.7259]]], dtype=torch.float64)


In [ ]:
print(u1.shape)
print(u2.shape)

In [ ]:
assert u1.all()==u2.all()

## Tensorly backend check

In [ ]:
import tensorly as tl
from tensorly.decomposition import parafac

In [ ]:
x = parafac(tensor, 3)
a, b, c = x[1][0], x[1][1], x[1][2]
print(type(a), type(b), type(c))

In [ ]:
tl.set_backend("pytorch")

In [ ]:
a = tl.unfold(torch_tensor, 0)

In [ ]:
print(type(a))

In [ ]:
x = parafac(torch_tensor, 3)

In [ ]:
a, b, c = x[1][0], x[1][1], x[1][2]

In [ ]:
print(type(a), type(b), type(c))